export type StructureLibraryCategory =
  | 'essentials'
  | 'amino-acids'
  | 'nucleotides'
  | 'sugars'
  | 'lipids'
  | 'protecting-groups'
  | 'medicines';

export interface StructureLibraryCategoryDefinition {
  id: StructureLibraryCategory;
  label: string;
  shortLabel: string;
  description: string;
}

export interface StructureLibraryEntry {
  id: string;
  name: string;
  aliases: string[];
  category: StructureLibraryCategory;
  formula: string;
  smiles: string;
  description: string;
  tags: string[];
  sourceUrl: string;
}

const pubchem = (name: string) =>
  `https://pubchem.ncbi.nlm.nih.gov/compound/${encodeURIComponent(name).replace(/%20/g, '-')}`;

export const STRUCTURE_LIBRARY_CATEGORIES: ReadonlyArray<StructureLibraryCategoryDefinition> = [
  {
    id: 'amino-acids',
    label: 'Aminoácidos',
    shortLabel: 'Aminoácidos',
    description: 'Bloques de construcción de proteínas con grupo amino y carboxilo.',
  },
  {
    id: 'nucleotides',
    label: 'Nucleótidos',
    shortLabel: 'Nucleótidos',
    description: 'Bases, pentosas y fosfatos de los ácidos nucleicos y del metabolismo.',
  },
  {
    id: 'sugars',
    label: 'Azúcares',
    shortLabel: 'Azúcares',
    description: 'Monosacáridos y disacáridos representativos.',
  },
  {
    id: 'lipids',
    label: 'Lípidos y ácidos grasos',
    shortLabel: 'Lípidos',
    description: 'Cadenas saturadas, insaturadas y un triacilglicérido sencillo.',
  },
  {
    id: 'protecting-groups',
    label: 'Grupos protectores',
    shortLabel: 'Protectores',
    description: 'Fragmentos con un punto R de conexión para síntesis y planificación.',
  },
  {
    id: 'medicines',
    label: 'Fármacos frecuentes',
    shortLabel: 'Fármacos',
    description: 'Principios activos conocidos para practicar reconocimiento estructural.',
  },
];

export const STRUCTURE_LIBRARY: ReadonlyArray<StructureLibraryEntry> = [
  {
    id: 'glycine',
    name: 'Glicina',
    aliases: ['Gly', 'ácido aminoacético'],
    category: 'amino-acids',
    formula: 'C₂H₅NO₂',
    smiles: 'NCC(=O)O',
    description: 'El aminoácido proteinogénico más pequeño; no posee centro quiral.',
    tags: ['aminoácido', 'proteína', 'zwitterion'],
    sourceUrl: pubchem('Glycine'),
  },
  {
    id: 'alanine',
    name: 'L-alanina',
    aliases: ['Ala', 'alanina'],
    category: 'amino-acids',
    formula: 'C₃H₇NO₂',
    smiles: 'N[C@@H](C)C(=O)O',
    description: 'Aminoácido apolar con una cadena lateral metilo.',
    tags: ['aminoácido', 'apolar', 'quiral'],
    sourceUrl: pubchem('L-Alanine'),
  },
  {
    id: 'valine',
    name: 'L-valina',
    aliases: ['Val', 'valina'],
    category: 'amino-acids',
    formula: 'C₅H₁₁NO₂',
    smiles: 'N[C@@H](C(C)C)C(=O)O',
    description: 'Aminoácido esencial de cadena lateral ramificada.',
    tags: ['aminoácido', 'esencial', 'BCAA'],
    sourceUrl: pubchem('L-Valine'),
  },
  {
    id: 'leucine',
    name: 'L-leucina',
    aliases: ['Leu', 'leucina'],
    category: 'amino-acids',
    formula: 'C₆H₁₃NO₂',
    smiles: 'N[C@@H](CC(C)C)C(=O)O',
    description: 'Aminoácido esencial hidrófobo y de cadena ramificada.',
    tags: ['aminoácido', 'esencial', 'BCAA'],
    sourceUrl: pubchem('L-Leucine'),
  },
  {
    id: 'serine',
    name: 'L-serina',
    aliases: ['Ser', 'serina'],
    category: 'amino-acids',
    formula: 'C₃H₇NO₃',
    smiles: 'N[C@@H](CO)C(=O)O',
    description: 'Aminoácido polar con un alcohol primario en la cadena lateral.',
    tags: ['aminoácido', 'polar', 'alcohol'],
    sourceUrl: pubchem('L-Serine'),
  },
  {
    id: 'phenylalanine',
    name: 'L-fenilalanina',
    aliases: ['Phe', 'fenilalanina'],
    category: 'amino-acids',
    formula: 'C₉H₁₁NO₂',
    smiles: 'N[C@@H](Cc1ccccc1)C(=O)O',
    description: 'Aminoácido aromático esencial con un grupo bencilo.',
    tags: ['aminoácido', 'aromático', 'esencial'],
    sourceUrl: pubchem('L-Phenylalanine'),
  },
  {
    id: 'amp',
    name: "Adenosín 5'-monofosfato",
    aliases: ['AMP', 'adenilato'],
    category: 'nucleotides',
    formula: 'C₁₀H₁₄N₅O₇P',
    smiles: 'NC1=NC=NC2=C1N=CN2C3OC(COP(=O)(O)O)C(O)C3O',
    description: 'Ribonucleótido de adenina y precursor de ADP, ATP y AMP cíclico.',
    tags: ['purina', 'ARN', 'fosfato'],
    sourceUrl: pubchem('Adenosine-monophosphate'),
  },
  {
    id: 'gmp',
    name: "Guanosín 5'-monofosfato",
    aliases: ['GMP', 'guanilato'],
    category: 'nucleotides',
    formula: 'C₁₀H₁₄N₅O₈P',
    smiles: 'NC1=NC2=C(N=CN2C3OC(COP(=O)(O)O)C(O)C3O)C(=O)N1',
    description: 'Ribonucleótido de guanina presente en ARN y rutas de señalización.',
    tags: ['purina', 'ARN', 'fosfato'],
    sourceUrl: pubchem('Guanosine-monophosphate'),
  },
  {
    id: 'cmp',
    name: "Citidín 5'-monofosfato",
    aliases: ['CMP', 'citidilato'],
    category: 'nucleotides',
    formula: 'C₉H₁₄N₃O₈P',
    smiles: 'NC1=NC=CC(=O)N1C2OC(COP(=O)(O)O)C(O)C2O',
    description: 'Ribonucleótido de citosina utilizado en la síntesis de ARN.',
    tags: ['pirimidina', 'ARN', 'fosfato'],
    sourceUrl: pubchem('Cytidine-monophosphate'),
  },
  {
    id: 'ump',
    name: "Uridín 5'-monofosfato",
    aliases: ['UMP', 'uridilato'],
    category: 'nucleotides',
    formula: 'C₉H₁₃N₂O₉P',
    smiles: 'O=C1NC=CC(=O)N1C2OC(COP(=O)(O)O)C(O)C2O',
    description: 'Ribonucleótido de uracilo e intermediario central de pirimidinas.',
    tags: ['pirimidina', 'ARN', 'fosfato'],
    sourceUrl: pubchem('Uridine-monophosphate'),
  },
  {
    id: 'dtmp',
    name: "Desoxitimidín 5'-monofosfato",
    aliases: ['dTMP', 'timidilato'],
    category: 'nucleotides',
    formula: 'C₁₀H₁₅N₂O₈P',
    smiles: 'CC1=CN(C(=O)NC1=O)C2CC(COP(=O)(O)O)OC2O',
    description: 'Desoxirribonucleótido de timina utilizado en el ADN.',
    tags: ['pirimidina', 'ADN', 'fosfato'],
    sourceUrl: pubchem('Thymidine-monophosphate'),
  },
  {
    id: 'atp',
    name: "Adenosín 5'-trifosfato",
    aliases: ['ATP', 'adenosín trifosfato'],
    category: 'nucleotides',
    formula: 'C₁₀H₁₆N₅O₁₃P₃',
    smiles: 'NC1=NC=NC2=C1N=CN2C3OC(COP(=O)(O)OP(=O)(O)OP(=O)(O)O)C(O)C3O',
    description: 'Nucleótido trifosfato que acopla transferencia de energía y fosforilación.',
    tags: ['purina', 'energía', 'trifosfato'],
    sourceUrl: pubchem('Adenosine-triphosphate'),
  },
  {
    id: 'glucose',
    name: 'D-glucosa',
    aliases: ['glucosa', 'dextrosa'],
    category: 'sugars',
    formula: 'C₆H₁₂O₆',
    smiles: 'OC[C@H]1O[C@@H](O)[C@H](O)[C@@H](O)[C@H]1O',
    description: 'Aldohexosa y combustible metabólico fundamental.',
    tags: ['monosacárido', 'hexosa', 'aldosa'],
    sourceUrl: pubchem('D-Glucose'),
  },
  {
    id: 'fructose',
    name: 'D-fructosa',
    aliases: ['fructosa', 'levulosa'],
    category: 'sugars',
    formula: 'C₆H₁₂O₆',
    smiles: 'OCC(O)C(O)C(O)C(=O)CO',
    description: 'Cetohexosa común en frutas y constituyente de la sacarosa.',
    tags: ['monosacárido', 'hexosa', 'cetosa'],
    sourceUrl: pubchem('D-Fructose'),
  },
  {
    id: 'ribose',
    name: 'D-ribosa',
    aliases: ['ribosa'],
    category: 'sugars',
    formula: 'C₅H₁₀O₅',
    smiles: 'OC[C@H]1O[C@@H](O)[C@H](O)[C@H]1O',
    description: 'Aldopentosa que forma el esqueleto de los ribonucleótidos.',
    tags: ['monosacárido', 'pentosa', 'ARN'],
    sourceUrl: pubchem('D-Ribose'),
  },
  {
    id: 'deoxyribose',
    name: '2-desoxi-D-ribosa',
    aliases: ['desoxirribosa'],
    category: 'sugars',
    formula: 'C₅H₁₀O₄',
    smiles: 'OC[C@H]1O[C@@H](O)C[C@H]1O',
    description: 'Pentosa del ADN, con un oxígeno menos que la ribosa.',
    tags: ['monosacárido', 'pentosa', 'ADN'],
    sourceUrl: pubchem('2-Deoxy-D-ribose'),
  },
  {
    id: 'sucrose',
    name: 'Sacarosa',
    aliases: ['azúcar de mesa', 'sucrosa'],
    category: 'sugars',
    formula: 'C₁₂H₂₂O₁₁',
    smiles: 'OCC1OC(O)(CO)C(O)C1OC2OC(CO)C(O)C(O)C2O',
    description: 'Disacárido formado por unidades de glucosa y fructosa.',
    tags: ['disacárido', 'glucosa', 'fructosa'],
    sourceUrl: pubchem('Sucrose'),
  },
  {
    id: 'lactose',
    name: 'Lactosa',
    aliases: ['azúcar de la leche'],
    category: 'sugars',
    formula: 'C₁₂H₂₂O₁₁',
    smiles: 'OCC1OC(OC2C(O)C(O)OC(CO)C2O)C(O)C(O)C1O',
    description: 'Disacárido compuesto por galactosa y glucosa.',
    tags: ['disacárido', 'galactosa', 'glucosa'],
    sourceUrl: pubchem('Lactose'),
  },
  {
    id: 'palmitic-acid',
    name: 'Ácido palmítico',
    aliases: ['ácido hexadecanoico', 'C16:0'],
    category: 'lipids',
    formula: 'C₁₆H₃₂O₂',
    smiles: 'CCCCCCCCCCCCCCCC(=O)O',
    description: 'Ácido graso saturado de dieciséis carbonos.',
    tags: ['ácido graso', 'saturado', 'C16'],
    sourceUrl: pubchem('Palmitic-acid'),
  },
  {
    id: 'stearic-acid',
    name: 'Ácido esteárico',
    aliases: ['ácido octadecanoico', 'C18:0'],
    category: 'lipids',
    formula: 'C₁₈H₃₆O₂',
    smiles: 'CCCCCCCCCCCCCCCCCC(=O)O',
    description: 'Ácido graso saturado de dieciocho carbonos.',
    tags: ['ácido graso', 'saturado', 'C18'],
    sourceUrl: pubchem('Stearic-acid'),
  },
  {
    id: 'oleic-acid',
    name: 'Ácido oleico',
    aliases: ['ácido cis-9-octadecenoico', 'C18:1'],
    category: 'lipids',
    formula: 'C₁₈H₃₄O₂',
    smiles: 'CCCCCCCCC=CCCCCCCCC(=O)O',
    description: 'Ácido graso monoinsaturado abundante en el aceite de oliva.',
    tags: ['ácido graso', 'monoinsaturado', 'C18'],
    sourceUrl: pubchem('Oleic-acid'),
  },
  {
    id: 'linoleic-acid',
    name: 'Ácido linoleico',
    aliases: ['C18:2', 'omega-6'],
    category: 'lipids',
    formula: 'C₁₈H₃₂O₂',
    smiles: 'CCCCCC=CCC=CCCCCCCCC(=O)O',
    description: 'Ácido graso poliinsaturado esencial de la familia omega-6.',
    tags: ['ácido graso', 'poliinsaturado', 'omega-6'],
    sourceUrl: pubchem('Linoleic-acid'),
  },
  {
    id: 'linolenic-acid',
    name: 'Ácido α-linolénico',
    aliases: ['ALA', 'C18:3', 'omega-3'],
    category: 'lipids',
    formula: 'C₁₈H₃₀O₂',
    smiles: 'CCC=CCC=CCC=CCCCCCCCC(=O)O',
    description: 'Ácido graso esencial poliinsaturado de la familia omega-3.',
    tags: ['ácido graso', 'poliinsaturado', 'omega-3'],
    sourceUrl: pubchem('Alpha-Linolenic-acid'),
  },
  {
    id: 'triacetin',
    name: 'Triacetina',
    aliases: ['triacetato de glicerilo', 'glicerol triacetato'],
    category: 'lipids',
    formula: 'C₉H₁₄O₆',
    smiles: 'CC(=O)OCC(COC(=O)C)OC(=O)C',
    description: 'Triéster compacto útil para estudiar el motivo de un triacilglicérido.',
    tags: ['triacilglicérido', 'éster', 'glicerol'],
    sourceUrl: pubchem('Triacetin'),
  },
  {
    id: 'boc-group',
    name: 'Grupo Boc',
    aliases: ['tert-butoxicarbonilo', 'Boc'],
    category: 'protecting-groups',
    formula: 'R–CO₂C(CH₃)₃',
    smiles: '*C(=O)OC(C)(C)C',
    description: 'Fragmento protector de aminas; R marca el punto de unión editable.',
    tags: ['amina', 'carbamato', 'fragmento R'],
    sourceUrl: pubchem('Di-tert-butyl-dicarbonate'),
  },
  {
    id: 'cbz-group',
    name: 'Grupo Cbz',
    aliases: ['carbobenciloxi', 'Z'],
    category: 'protecting-groups',
    formula: 'R–CO₂CH₂Ph',
    smiles: '*C(=O)OCc1ccccc1',
    description: 'Carbamato bencílico utilizado habitualmente para proteger aminas.',
    tags: ['amina', 'carbamato', 'bencilo'],
    sourceUrl: pubchem('Benzyl-chloroformate'),
  },
  {
    id: 'fmoc-group',
    name: 'Grupo Fmoc',
    aliases: ['fluorenilmetoxicarbonilo', 'Fmoc'],
    category: 'protecting-groups',
    formula: 'R–CO₂CH₂–fluorenilo',
    smiles: '*C(=O)OCC1c2ccccc2c3ccccc13',
    description: 'Protector de aminas muy usado en síntesis de péptidos en fase sólida.',
    tags: ['amina', 'péptido', 'fluoreno'],
    sourceUrl: pubchem('Fmoc-chloride'),
  },
  {
    id: 'benzyl-group',
    name: 'Grupo bencilo',
    aliases: ['Bn', 'benzyl'],
    category: 'protecting-groups',
    formula: 'R–CH₂Ph',
    smiles: '*Cc1ccccc1',
    description: 'Fragmento bencílico empleado para proteger alcoholes, ácidos y aminas.',
    tags: ['alcohol', 'éter', 'benceno'],
    sourceUrl: pubchem('Benzyl-bromide'),
  },
  {
    id: 'acetyl-group',
    name: 'Grupo acetilo',
    aliases: ['Ac', 'etanoilo'],
    category: 'protecting-groups',
    formula: 'R–COCH₃',
    smiles: '*C(=O)C',
    description: 'Protección acilo sencilla para alcoholes y aminas.',
    tags: ['alcohol', 'amina', 'acilo'],
    sourceUrl: pubchem('Acetic-anhydride'),
  },
  {
    id: 'tbdms-group',
    name: 'Grupo TBDMS',
    aliases: ['TBS', 'tert-butildimetilsililo'],
    category: 'protecting-groups',
    formula: 'R–Si(CH₃)₂C(CH₃)₃',
    smiles: '*[Si](C)(C)C(C)(C)C',
    description: 'Éter de sililo robusto para proteger grupos hidroxilo.',
    tags: ['alcohol', 'sililo', 'éter'],
    sourceUrl: pubchem('tert-Butyldimethylsilyl-chloride'),
  },
  {
    id: 'aspirin',
    name: 'Ácido acetilsalicílico',
    aliases: ['aspirina', 'ASA'],
    category: 'medicines',
    formula: 'C₉H₈O₄',
    smiles: 'CC(=O)Oc1ccccc1C(=O)O',
    description: 'Analgésico y antiagregante con grupos éster y ácido carboxílico.',
    tags: ['analgésico', 'éster', 'aromático'],
    sourceUrl: pubchem('Aspirin'),
  },
  {
    id: 'paracetamol',
    name: 'Paracetamol',
    aliases: ['acetaminofén', 'APAP'],
    category: 'medicines',
    formula: 'C₈H₉NO₂',
    smiles: 'CC(=O)Nc1ccc(O)cc1',
    description: 'Analgésico con una amida y un fenol sobre un anillo aromático.',
    tags: ['analgésico', 'amida', 'fenol'],
    sourceUrl: pubchem('Acetaminophen'),
  },
  {
    id: 'ibuprofen',
    name: 'Ibuprofeno',
    aliases: ['ácido 2-(4-isobutilfenil)propanoico'],
    category: 'medicines',
    formula: 'C₁₃H₁₈O₂',
    smiles: 'CC(C)Cc1ccc(cc1)C(C)C(=O)O',
    description: 'Antiinflamatorio no esteroideo con un ácido carboxílico quiral.',
    tags: ['AINE', 'analgésico', 'ácido carboxílico'],
    sourceUrl: pubchem('Ibuprofen'),
  },
  {
    id: 'naproxen',
    name: 'Naproxeno',
    aliases: ['S-naproxeno'],
    category: 'medicines',
    formula: 'C₁₄H₁₄O₃',
    smiles: 'COc1ccc2cc(ccc2c1)[C@@H](C)C(=O)O',
    description: 'AINE aromático con centro quiral y grupo metoxi.',
    tags: ['AINE', 'analgésico', 'quiral'],
    sourceUrl: pubchem('Naproxen'),
  },
  {
    id: 'caffeine',
    name: 'Cafeína',
    aliases: ['1,3,7-trimetilxantina'],
    category: 'medicines',
    formula: 'C₈H₁₀N₄O₂',
    smiles: 'CN1C=NC2=C1C(=O)N(C(=O)N2C)C',
    description: 'Metilxantina estimulante con un sistema heterocíclico conjugado.',
    tags: ['estimulante', 'xantina', 'heterociclo'],
    sourceUrl: pubchem('Caffeine'),
  },
  {
    id: 'metformin',
    name: 'Metformina',
    aliases: ['dimetilbiguanida'],
    category: 'medicines',
    formula: 'C₄H₁₁N₅',
    smiles: 'CN(C)C(=N)NC(=N)N',
    description: 'Biguanida usada como ejemplo de molécula nitrogenada básica.',
    tags: ['antidiabético', 'biguanida', 'amina'],
    sourceUrl: pubchem('Metformin'),
  },
];

export const STRUCTURE_LIBRARY_BY_ID = new Map(
  STRUCTURE_LIBRARY.map((entry) => [entry.id, entry] as const),
);

const ESSENTIAL_IDENTIFICATION_REFERENCES: ReadonlyArray<StructureLibraryEntry> = [
  {
    id: 'ethanol',
    name: 'Etanol',
    aliases: ['alcohol etílico'],
    category: 'essentials',
    formula: 'C₂H₆O',
    smiles: 'CCO',
    description: 'Alcohol sencillo de dos carbonos.',
    tags: ['alcohol', 'orgánica'],
    sourceUrl: pubchem('Ethanol'),
  },
  {
    id: 'water',
    name: 'Agua',
    aliases: ['óxido de dihidrógeno'],
    category: 'essentials',
    formula: 'H₂O',
    smiles: 'O',
    description: 'Molécula angular esencial para la química y la vida.',
    tags: ['inorgánica', 'disolvente'],
    sourceUrl: pubchem('Water'),
  },
  {
    id: 'methane',
    name: 'Metano',
    aliases: ['CH4'],
    category: 'essentials',
    formula: 'CH₄',
    smiles: 'C',
    description: 'El hidrocarburo saturado más pequeño.',
    tags: ['alcano', 'orgánica'],
    sourceUrl: pubchem('Methane'),
  },
  {
    id: 'ammonia',
    name: 'Amoniaco',
    aliases: ['NH3'],
    category: 'essentials',
    formula: 'NH₃',
    smiles: 'N',
    description: 'Hidruro de nitrógeno con geometría piramidal.',
    tags: ['inorgánica', 'base'],
    sourceUrl: pubchem('Ammonia'),
  },
  {
    id: 'carbon-dioxide',
    name: 'Dióxido de carbono',
    aliases: ['CO2', 'anhídrido carbónico'],
    category: 'essentials',
    formula: 'CO₂',
    smiles: 'O=C=O',
    description: 'Molécula lineal con dos enlaces dobles.',
    tags: ['inorgánica', 'carbonilo'],
    sourceUrl: pubchem('Carbon-dioxide'),
  },
  {
    id: 'sulfuric-acid',
    name: 'Ácido sulfúrico',
    aliases: ['H2SO4'],
    category: 'essentials',
    formula: 'H₂SO₄',
    smiles: 'OS(=O)(=O)O',
    description: 'Oxoácido de azufre con dos grupos hidroxilo.',
    tags: ['inorgánica', 'ácido'],
    sourceUrl: pubchem('Sulfuric-acid'),
  },
  {
    id: 'benzene',
    name: 'Benceno',
    aliases: ['benzol'],
    category: 'essentials',
    formula: 'C₆H₆',
    smiles: 'c1ccccc1',
    description: 'Anillo aromático de seis miembros.',
    tags: ['aromático', 'anillo'],
    sourceUrl: pubchem('Benzene'),
  },
];

export const IDENTIFICATION_REFERENCES: ReadonlyArray<StructureLibraryEntry> = [
  ...ESSENTIAL_IDENTIFICATION_REFERENCES,
  ...STRUCTURE_LIBRARY,
];

export const IDENTIFICATION_REFERENCE_BY_ID = new Map(
  IDENTIFICATION_REFERENCES.map((entry) => [entry.id, entry] as const),
);
